---
# YUMのパッケージリストを最新に更新
- name: Update YUM package list
  become: yes
  yum:
    update_cache: yes
  tags: yum

# 全てのパッケージを最新バージョンに更新
- name: Upgrade all packages to the latest version
  become: yes
  yum:
    name: "*"
    state: latest
  tags: yum

# 必要なパッケージをインストール
- name: Install necessary packages
  become: yes
  yum:
    name:
      - git
      - gcc-c++
      - patch
      - bzip2
      - openssl-devel
      - libyaml-devel
      - libffi-devel
      - readline-devel
      - zlib-devel
      - gdbm-devel
      - ncurses-devel
      - make
      - curl
      - ImageMagick-devel
      - libcurl-devel
      - libicu-devel
      - libxml2-devel
      - libxslt-devel
    state: present
  tags: packages
