version: 2.1
orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@3.1.5
  ansible: orbss/ansible-playbook@0.0.5
  ruby: circleci/ruby@2.0.0

commands:
  setup-ssh-config:
    description: "Setup SSH configuration"
    steps:
      - run:
          name: Load EC2 IP Address from File and Setup SSH Config
          command: |
            if [ -f /tmp/ec2_ip.txt ]; then
              TARGET_HOST=$(cat /tmp/ec2_ip.txt)
              echo "Loaded TARGET_HOST as $TARGET_HOST"
              echo -e "Host raisetech-lecture10-ec2\n  HostName ${TARGET_HOST}\n  Port 22\n  User ec2-user\n  IdentityFile ~/.ssh/id_rsa\n  StrictHostKeyChecking no" > ~/.ssh/config
            else
              echo "Failed to load IP Address from file"
              exit 1
            fi

jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml
          when: always
          no_output_timeout: 5m

  cfn-execute:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run: aws cloudformation deploy --template-file cloudformation/vpc.yml --stack-name raisetech-lecture10-vpc
      - run: aws cloudformation deploy --template-file cloudformation/ec2.yml --stack-name raisetech-lecture10-ec2 --capabilities CAPABILITY_IAM
      - run: aws cloudformation deploy --template-file cloudformation/rds.yml --stack-name raisetech-lecture10-rds
      - run: aws cloudformation deploy --template-file cloudformation/elb.yml --stack-name raisetech-lecture10-elb
      - run: aws cloudformation deploy --template-file cloudformation/s3.yml --stack-name raisetech-lecture10-s3

  get-ec2-ip:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run:
          name: Fetch EC2 IP Address by Tag and Save to File
          command: |
            IP_ADDRESS=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=raisetech-lecture10-ec2" --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
            if [ -z "$IP_ADDRESS" ]; then
              echo "Failed to fetch IP Address"
              exit 1
            fi
            echo "$IP_ADDRESS" > /tmp/ec2_ip.txt
      - persist_to_workspace:
          root: /tmp
          paths:
            - ec2_ip.txt

  get-rds-endpoint:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run:
          name: Fetch RDS Endpoint by Stack Output and Save to File
          command: |
            ENDPOINT=$(aws cloudformation describe-stacks --stack-name raisetech-lecture10-rds --query "Stacks[0].Outputs[?OutputKey=='RDS'].OutputValue" --output text)
            if [ -z "$ENDPOINT" ]; then
              echo "Failed to fetch RDS Endpoint"
              exit 1
            fi
            echo "$ENDPOINT" > /tmp/rds_endpoint.txt
      - persist_to_workspace:
          root: /tmp
          paths:
            - rds_endpoint.txt

  ansible-execute:
    executor: ansible/default
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - setup-ssh-config
      - run:
          name: Load RDS Endpoint from File
          command: |
            if [ -f /tmp/rds_endpoint.txt ]; then
              echo "export AWS_DB_HOST=$(cat /tmp/rds_endpoint.txt)" >> $BASH_ENV
            else
              echo "Failed to load RDS Endpoint from file"
              exit 1
            fi
      - ansible/install:
          version: 2.9.23
      - ansible/playbook:
          playbook: ansible/playbook.yml
          playbook-options: "-i ansible/inventory"

  serverspec-execute:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - setup-ssh-config
      - run:
          name: Check SSH Config
          command: cat ~/.ssh/config
      - run:
          name: bundle install
          command: |
            cd serverspec
            bundle install --path vendor/bundle
      - run:
          name: Directly execute serverspec
          command: |
            cd serverspec
            TARGET_HOST=raisetech-ec2 bundle exec rspec spec/raisetech-ec2/sample_spec.rb
      - run:
          name: execute serverspec
          command: |
            cd serverspec
            bundle exec rake spec


workflows:
  raisetech:
    jobs:
      - cfn-lint
      - cfn-execute:
          requires:
            - cfn-lint
      - get-ec2-ip:
          requires:
            - cfn-execute
      - get-rds-endpoint:
          requires:
            - cfn-execute
      - ansible-execute:
          requires:
            - get-ec2-ip
            - get-rds-endpoint
      - serverspec-execute:
          requires:
            - ansible-execute
