- name: check yarn install
  shell: bash -lc "yarn --version | grep {{ yarn_version }}"
  register: yarn_version_check
  changed_when: no
  ignore_errors: yes

- name: Install Yarn if not present
  shell: bash -lc "npm install --global yarn@{{ yarn_version }}"
  when: yarn_version_check is failed
