---
# MariaDBを削除
- name: Remove MariaDB
  become: true
  yum:
    name: mariadb-server
    state: absent

# MySQLのリポジトリをインストール
- name: Install MySQL repository
  become_user: root
  yum:
    name: 'https://repo.mysql.com//mysql80-community-release-el7-7.noarch.rpm'
    state: present
  register: mysql_installed

# GPGキーをインポート
- name: Import GPG key for MySQL
  become_user: root
  ansible.builtin.rpm_key:
    state: present
    key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
  when: mysql_installed.changed

# MySQLのクライアントをインストール
- name: Install MySQL client
  become_user: root
  yum:
    name: mysql-community-client
    state: present
  when: mysql_installed.changed

# MySQLの開発ツールをインストール
- name: Install MySQL development tools
  become_user: root
  yum:
    name: mysql-community-devel
    state: present
  when: mysql_installed.changed

# アプリケーションの初期セットアップを実行
- name: Run application setup script
  shell: bash -lc "bin/setup"
  args:
    chdir: "{{ sample_app_dir }}"
  when: mysql_installed.changed

# アセットを事前コンパイル
- name: Precompile application assets
  shell: bash -lc "rails assets:precompile"
  args:
    chdir: "{{ sample_app_dir }}"
