# Railsのバージョンを確認するタスク
- name: Check Rails version
  shell: bash -lc "gem list -e rails | grep {{ rails_version }}"
  register: rails_version_check
  changed_when: no
  ignore_errors: yes

# 指定されたバージョンのRailsが存在しなければ、インストールするタスク
- name: Install Rails if not present
  gem:
    name: rails
    version: "{{ rails_version }}"
    executable: /home/ec2-user/.rbenv/shims/gem
    user_install: no
  when: rails_version_check is failed
