---
# Bundlerのバージョンを確認して、必要なバージョンがインストールされているかを判定
- name: Check Bundler version
  command: bundler version
  register: bundler_version_check
  changed_when: false
  failed_when: false
  tags: bundler

# 必要なバージョンのBundlerがインストールされていない場合のみ、インストールする
- name: Install Bundler if necessary
  gem:
    name: bundler
    version: "{{ bundler_version }}"
    executable: /home/ec2-user/.rbenv/shims/gem
    user_install: no
  when: bundler_version_check.stdout != "Bundler version {{ bundler_version }}"
  tags: bundler
