AWSTemplateFormatVersion: 2010-09-09
Description: 第10回課題ALB

Parameters:
  Project:
    Type: String
    Default: raisetech-lecture10

Resources:

# セキュリティグループ
  Lec10ElbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub This Security Group is for ${Project}
      VpcId: !ImportValue VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

# ロードバランサー
  Lec10ELB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${Project}-elb
      Scheme: internet-facing
      IpAddressType: ipv4
      Subnets:
        - !ImportValue PublicSubnet1a
        - !ImportValue PublicSubnet1c
      SecurityGroups:
        - !Ref Lec10ElbSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${Project}-elb

# ターゲットグループ
  Lec10ElbTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      TargetType: instance
      Name: !Sub ${Project}-elb-tg
      Protocol: HTTP
      Port: 80
      VpcId: !ImportValue VPC
      ProtocolVersion: HTTP1
      HealthCheckProtocol: HTTP
      HealthCheckPath: /
      Targets:
        - Id: !ImportValue EC2

# リスナー
  Lec10ElbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref Lec10ELB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref Lec10ElbTargetGroup

Outputs:
  ELBSg:
    Value: !Ref Lec10ElbSecurityGroup
    Export:
      Name: ELBSg
